### PR TITLE
fix: update group tabs after tab rename

### LINKED ISSUE #2: [BUG]: Renaming a tab removes it from the group
# Description
Renaming a tab (a note) inside a tab group it is currently in, causes it to be removed from that group.

**Steps to reproduce** 
1. create a tab group 
2. add a note to it
3. rename that note 

> Also, renaming it to its original name brings it back to the group

# Expected Behavior
Note should stay in its current tab group.

### PR DESCRIPTION
**Pull request by HelanaNady**
# Description
- Renaming a tab inside a group caused it to be removed from its current group so I added an event handler for file renames to update the group with the new path.

> While working on this, I also noticed that `data.json` is never updated when a note inside a group is deleted so if you create a note, delete it, create a new note with the same title, it will appear in that group xd
I'll open another follow PR to address this issue.

# References
- fixes #2 

# Pull Request Checklist

- [x] Code builds without errors (`npm run build`)
- [x] Linter passes (`npm run lint`)
- [x] Manually tested in Obsidian (create, rename, recolor, collapse, delete, reload)
- [x] No unrelated changes included
- [x] Commit messages are clear and descriptive

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -77,6 +77,11 @@ export default class TabGroupsPlugin extends Plugin {
     this.registerEvent(
       this.app.workspace.on("active-leaf-change", () => this.render()),
     );
+    this.app.vault.on("rename", (file, oldPath) => {
+      setTimeout(() => {
+        this.groupManager.handleFileRename(file, oldPath);
+      }, 0);
+    });
```
Comment (habibayman) [inline src/main.ts]: can you use a `registerEvent` for this instead? I don't think the `setTimeout` is needed.

```suggestion
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        this.groupManager.handleFileRename(file, oldPath);
      }),
    );
```

**Comment by habibayman** [comment]
> also noticed that data.json is never updated when a note inside a group is deleted 

I think the `id` combination for a tab in a group in general needs to change, it will help solve #9 too and the issue you prescribed will get solved along the way.

**Comment by HelanaNady** [comment]
> I think the `id` combination for a tab in a group

I’ll have a look at this before working on that issue.
